"""Ikariam Gameforge login service.

Authentication flow (validated against real servers June 2026):

1. POST spark-web.gameforge.com/api/v2/authProviders/mauth/sessions
   - Payload: identity, password, locale, gfLang, gameId, gameEnvironmentId, blackbox
   - The blackbox token is generated by challenge.gameforge.com JS and encodes
     browser fingerprint. A valid blackbox bypasses captcha.
   - If blackbox is invalid/untrusted: returns 409 CREDENTIALS_INVALID (misleading)
   - If credentials wrong: returns 409 CREDENTIALS_INVALID
   - If success: returns session token

2. Alternative: POST spark-web.gameforge.com/api/v2/authProviders/credentials/sessions
   - Payload: email, password, locale, blackbox
   - Always requires solving a challenge (gf-image-drop-captcha)
   - Returns challengeId that must be solved before login completes

3. After auth: use the session token to call lobby APIs:
   - GET lobby.ikariam.gameforge.com/api/users/me/accounts (list game accounts)
   - GET lobby.ikariam.gameforge.com/api/servers (list available servers)
   - POST lobby.ikariam.gameforge.com/api/users/me/loginLink
     body: {server: {language, number}, clickedButton: "account_list", id, blackbox}

4. The loginLink returns a URL that logs into the specific game world.
"""

import aiohttp
from aiohttp_socks import ProxyConnector
from yarl import URL
from typing import Optional
import json
import re
import logging

from app.services.ikariam.endpoints import (
    SPARK_LOGIN_MAUTH,
    SPARK_LOGIN_CREDENTIALS,
    CHALLENGE_BASE,
    LOBBY_ACCOUNTS,
    LOBBY_SERVERS,
    LOBBY_LOGIN_LINK,
    LOBBY_HEADERS,
    DEFAULT_HEADERS,
    IKARIAM_PLATFORM_GAME_ID,
    IKARIAM_GAME_ENVIRONMENT_ID,
    generate_installation_id,
)
from app.utils.humanizer import random_delay
from app.services.ikariam.lobby_decaptcha import break_interactive_captcha

logger = logging.getLogger(__name__)


class GameforgeLoginError(Exception):
    """Raised when login fails."""

    def __init__(self, message: str, error_type: str = "UNKNOWN", challenge_id: str = ""):
        super().__init__(message)
        self.error_type = error_type
        self.challenge_id = challenge_id


class IkariamLoginService:
    """Handles the Gameforge Spark API login flow."""

    def __init__(self, proxy_url: Optional[str] = None):
        self.proxy_url = proxy_url
        self.session: Optional[aiohttp.ClientSession] = None
        self.auth_token: Optional[str] = None
        self.installation_id: str = generate_installation_id()
        self.accounts: list = []
        self.servers: list = []

    def _get_connector(self):
        if self.proxy_url:
            return ProxyConnector.from_url(self.proxy_url)
        return aiohttp.TCPConnector(ssl=False)

    async def create_session(self) -> aiohttp.ClientSession:
        connector = self._get_connector()
        self.session = aiohttp.ClientSession(
            connector=connector,
            headers=DEFAULT_HEADERS,
        )
        return self.session

    async def close(self):
        if self.session:
            await self.session.close()
            self.session = None

    def _set_lobby_cookie(self, token: str) -> None:
        """Set the gf-token-production lobby cookie (manual-token fallback)."""
        self.session.cookie_jar.update_cookies(
            {"gf-token-production": token},
            response_url=URL("https://lobby.ikariam.gameforge.com"),
        )

    async def login(
        self,
        email: str,
        password: str,
        locale: str = "en-GB",
        gf_lang: str = "en",
        blackbox: str = "",
        gf_token: str = "",
    ) -> dict:
        """
        Full Gameforge login flow:
        1. Authenticate via Spark API (mauth endpoint)
        2. Get game accounts
        3. Get servers info
        4. Return accounts, servers, and auth token

        Args:
            email: Gameforge account email
            password: Account password
            locale: Locale in format 'xx-XX' (e.g. 'en-GB', 'pt-BR')
            gf_lang: Gameforge language code (e.g. 'en', 'pt', 'de')
            blackbox: Challenge token from browser (required for mauth)

        Returns:
            dict with accounts, servers, and token
        """
        if not self.session:
            await self.create_session()

        # Step 1: Authenticate. A manually-provided gf-token-production bypasses
        # the whole Spark/challenge flow (Ikabot's manual-token fallback).
        if gf_token:
            self.auth_token = gf_token.strip().split("=")[-1]
            self._set_lobby_cookie(self.auth_token)
        else:
            self.auth_token = await self._authenticate_mauth(
                email, password, locale, gf_lang, blackbox
            )
        await random_delay(1.0, 2.0)

        # Step 2: Get available accounts
        accounts = await self._get_accounts()
        await random_delay(0.5, 1.0)

        # Step 3: Get servers info
        servers = await self._get_servers()

        return {
            "token": self.auth_token,
            "accounts": accounts,
            "servers": servers,
        }

    async def _authenticate_mauth(
        self,
        email: str,
        password: str,
        locale: str,
        gf_lang: str,
        blackbox: str,
    ) -> str:
        """
        Authenticate using the mauth (managed auth) endpoint.
        This is the primary login method used by the Ikariam lobby.

        The blackbox token is critical - it must come from a trusted browser
        environment. Without a valid blackbox, the server returns CREDENTIALS_INVALID.
        """
        payload = {
            "identity": email,
            "password": password,
            "locale": locale,
            "gfLang": gf_lang,
            "gameId": IKARIAM_PLATFORM_GAME_ID,
            "gameEnvironmentId": IKARIAM_GAME_ENVIRONMENT_ID,
            "blackbox": blackbox,
        }

        headers = {
            **LOBBY_HEADERS,
            "tnt-installation-id": self.installation_id,
            "gf-installation-id": self.installation_id,
        }

        # Gameforge may answer with an interactive "challenge" (image-drop
        # captcha) instead of a token. Solve it and retry a few times, like
        # Ikabot does.
        for _attempt in range(4):
            async with self.session.post(
                SPARK_LOGIN_MAUTH,
                json=payload,
                headers=headers,
            ) as resp:
                text = await resp.text()
                status = resp.status
                challenge_header = resp.headers.get("gf-challenge-id", "")

            if status in (200, 201):
                data = json.loads(text)
                token = data.get("token", "")
                logger.info("Login successful via mauth")
                return token

            # An interactive challenge is required: solve it, then retry login.
            if challenge_header and "token" not in text:
                challenge_id = challenge_header.split(";")[0]
                solved = await self._solve_interactive_challenge(challenge_id)
                if not solved:
                    raise GameforgeLoginError(
                        "A Gameforge pediu um desafio (captcha de login) e nao "
                        "foi possivel resolve-lo automaticamente. Faca login uma "
                        "vez pelo navegador em lobby.ikariam.gameforge.com para "
                        "limpar e tente de novo.",
                        error_type="CHALLENGE_REQUIRED",
                        challenge_id=challenge_id,
                    )
                # Loop again to re-attempt the login with the solved challenge.
                continue

            if status == 409:
                try:
                    data = json.loads(text)
                except json.JSONDecodeError:
                    raise GameforgeLoginError(f"Login failed: {text}")

                error_types = data.get("errorTypes", [])
                if "CREDENTIALS_INVALID" in error_types:
                    raise GameforgeLoginError(
                        "Invalid credentials or untrusted blackbox",
                        error_type="CREDENTIALS_INVALID",
                    )
                raise GameforgeLoginError(
                    f"Login conflict: {data.get('message', text)}",
                    error_type=error_types[0] if error_types else "UNKNOWN",
                )

            if status == 403:
                raise GameforgeLoginError(
                    "Account blocked or too many attempts",
                    error_type="BLOCKED",
                )

            raise GameforgeLoginError(
                f"Login failed with status {status}: {text}",
                error_type="HTTP_ERROR",
            )

        raise GameforgeLoginError(
            "Nao foi possivel completar o login apos resolver o desafio varias "
            "vezes. Tente novamente em instantes.",
            error_type="CHALLENGE_REQUIRED",
        )

    async def _solve_interactive_challenge(self, challenge_id: str) -> bool:
        """Solve Gameforge's image-drop login challenge.

        Fetches the text image + 4 drag icons, matches them with the local
        model (ported from Ikabot's ``lobbyDecaptcha``) and submits the answer.
        Returns True when the challenge is reported as solved.
        """
        base = f"https://image-drop-challenge.gameforge.com/challenge/{challenge_id}/en-GB"
        ch_headers = {
            "Accept": "*/*",
            "Origin": "https://lobby.ikariam.gameforge.com",
            "Referer": "https://lobby.ikariam.gameforge.com/",
        }
        try:
            # Warm-up requests mirroring the browser flow.
            await self.session.get(
                f"{CHALLENGE_BASE}/challenge/{challenge_id}", headers=ch_headers
            )
            await self.session.get(
                "https://image-drop-challenge.gameforge.com/index.js", headers=ch_headers
            )
            try:
                await self.session.post(
                    "https://pixelzirkus.gameforge.com/do2/simple", headers=ch_headers
                )
            except Exception:
                pass

            async with self.session.get(base, headers=ch_headers) as resp:
                meta = await resp.json()
            captcha_time = meta.get("lastUpdated", "")

            async with self.session.get(
                f"{base}/text?{captcha_time}", headers=ch_headers
            ) as resp:
                text_image = await resp.read()
            async with self.session.get(
                f"{base}/drag-icons?{captcha_time}", headers=ch_headers
            ) as resp:
                drag_icons = await resp.read()

            answer = break_interactive_captcha(text_image, drag_icons)
            async with self.session.post(
                base, json={"answer": answer}, headers=ch_headers
            ) as resp:
                result = await resp.json()
            return result.get("status") == "solved"
        except Exception as e:  # noqa: BLE001
            logger.warning("Interactive challenge solve failed: %s", e)
            return False

    async def login_with_credentials(
        self,
        email: str,
        password: str,
        locale: str = "en-GB",
        blackbox: str = "",
    ) -> dict:
        """
        Alternative login using the credentials endpoint.
        This always returns a challenge that needs to be solved.

        Returns:
            dict with challengeId and challenge type info
        """
        if not self.session:
            await self.create_session()

        payload = {
            "email": email,
            "password": password,
            "locale": locale,
            "blackbox": blackbox,
        }

        headers = {
            **LOBBY_HEADERS,
            "tnt-installation-id": self.installation_id,
            "gf-installation-id": self.installation_id,
        }

        async with self.session.post(
            SPARK_LOGIN_CREDENTIALS,
            json=payload,
            headers=headers,
        ) as resp:
            text = await resp.text()
            data = json.loads(text)

            if resp.status in (200, 201):
                token = data.get("token", "")
                self.auth_token = token
                return {"token": token, "status": "success"}

            if resp.status == 409:
                challenge_id = data.get("challengeId", "")
                gf_challenge = resp.headers.get("GF-Challenge-Id", "")

                if "CHALLENGE_REQUIRED" in data.get("errorTypes", []):
                    challenge_info = await self._get_challenge_info(challenge_id)
                    return {
                        "status": "challenge_required",
                        "challenge_id": challenge_id,
                        "gf_challenge_header": gf_challenge,
                        "challenge_info": challenge_info,
                    }

                raise GameforgeLoginError(
                    data.get("message", "Login failed"),
                    error_type=data.get("errorTypes", ["UNKNOWN"])[0],
                )

            raise GameforgeLoginError(f"Login failed: {resp.status} {text}")

    async def _get_challenge_info(self, challenge_id: str) -> dict:
        """Get details about a challenge (captcha type, script URL)."""
        url = f"{CHALLENGE_BASE}/challenge/{challenge_id}"
        try:
            async with self.session.get(url) as resp:
                if resp.status == 200:
                    return await resp.json()
                return {"error": f"Challenge info failed: {resp.status}"}
        except Exception as e:
            return {"error": str(e)}

    async def _get_accounts(self) -> list:
        """Get all game accounts for the authenticated user."""
        headers = {
            **LOBBY_HEADERS,
            "Authorization": f"Bearer {self.auth_token}",
        }

        async with self.session.get(
            LOBBY_ACCOUNTS,
            headers=headers,
        ) as resp:
            if resp.status != 200:
                text = await resp.text()
                raise GameforgeLoginError(
                    f"Failed to get accounts: {resp.status} - {text}"
                )
            data = await resp.json()
            self.accounts = data if isinstance(data, list) else list(data.values())
            return self.accounts

    async def _get_servers(self) -> list:
        """Get available game servers."""
        headers = {
            **LOBBY_HEADERS,
            "Authorization": f"Bearer {self.auth_token}",
        }

        async with self.session.get(
            LOBBY_SERVERS,
            headers=headers,
        ) as resp:
            if resp.status != 200:
                return []
            data = await resp.json()
            self.servers = data if isinstance(data, list) else list(data.values())
            return self.servers

    async def get_login_link(
        self,
        account_id: str,
        server_language: str,
        server_number: int,
        blackbox: str = "",
    ) -> str:
        """Get the login link for a specific game world (POST with blackbox)."""
        if not self.auth_token:
            raise GameforgeLoginError("Not authenticated")

        headers = {
            **LOBBY_HEADERS,
            "Authorization": f"Bearer {self.auth_token}",
            "Content-Type": "application/json",
            "Origin": "https://lobby.ikariam.gameforge.com",
            "Referer": "https://lobby.ikariam.gameforge.com/en_GB/accounts",
        }

        payload = {
            "server": {
                "language": server_language,
                "number": server_number,
            },
            "clickedButton": "account_list",
            "id": account_id,
            "blackbox": blackbox,
        }

        async with self.session.post(
            LOBBY_LOGIN_LINK,
            json=payload,
            headers=headers,
        ) as resp:
            if resp.status != 200:
                text = await resp.text()
                raise GameforgeLoginError(
                    f"Failed to get login link: {resp.status} - {text}"
                )
            data = await resp.json()
            return data.get("url", "")

    async def login_to_world(self, login_url: str) -> dict:
        """Use the login link to enter the game world. Returns session cookies."""
        async with self.session.get(
            login_url,
            headers=DEFAULT_HEADERS,
            allow_redirects=True,
        ) as resp:
            if resp.status != 200:
                raise GameforgeLoginError(
                    f"Failed to login to world: {resp.status}"
                )

            cookies = {}
            for cookie in self.session.cookie_jar:
                cookies[cookie.key] = cookie.value

            text = await resp.text()

            # Derive the game server base URL from the final/redirected URL
            final_url = str(resp.url)
            m = re.search(r"(https://s\d+-\w+\.ikariam\.gameforge\.com)", final_url)
            if not m:
                m = re.search(r"(https://s\d+-\w+\.ikariam\.gameforge\.com)", login_url)
            server_url = m.group(1) if m else ""

            return {
                "cookies": cookies,
                "server_url": server_url,
                "html": text,
            }
